cmake_minimum_required(VERSION 3.16)

project(MyProject LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Collect all source files
file(GLOB_RECURSE SOURCES
    src/*.cpp
)

# Create executable (change name if you want)
add_executable(${PROJECT_NAME} ${SOURCES})

# Include header directory
target_include_directories(${PROJECT_NAME} PRIVATE include)